config/routes.rb
Rails.application.routes.draw do

  root    "home#welcome"
  get "mirraws/designs" => "mirraw#designs"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome

  end
end

app/controllers/mirraw_controller.rb
require 'open-uri'

class MirrawController < ApplicationController
	def designs
		doc = Nokogiri::HTML(open('http://www.mirraw.com/salwar-suits/anarkali-salwar-kameez'))

    all_brand_names = []
    doc.css('p.listing-maker.row a').each do |link|
      all_brand_names = all_brand_names + link.content.split(",")
    end

     @brands = []

     all_brand_names.uniq.each do |brand_name|
     	 @brands << { brand_name: brand_name, no_of_designs: all_brand_names.count(brand_name) }
     end
  
     @brands.sort_by! { |brand| brand[:no_of_designs] }
     @brands.reverse!
     @brands = @brands.take(3)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/welcome.html.erb
<h2>Welcome to Anarkali App</h2>
<%= link_to "Clicl here to get top 3 list anarakli brands", mirraws_designs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnarkaliApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</head>
	<body>

		<%= yield %>

	</body>
</html>

app/views/mirraw/designs.html.erb
<div class="container">
 <table class="table table-hover">
	<tr>
		<th>Desiger Brand Name</th>
		<th>Number Of Designs</th>
	</tr>
	
	<% @brands.each do |brand| %>
		<tr>
			<td><%= brand[:brand_name] %></td>
			<td><%= brand[:no_of_designs] %></td>
		</tr>
  <% end %>
 </table>

<br/>
<br/>
<%= link_to "Refresh", mirraws_designs_path %>
</div>